const csrf = await fetch("https://playentry.org");
const body = await csrf.text();
const index = body.indexOf("csrf-token") + 21;
const csrfToken = body.slice(index, index + 36);

setInterval(function () {for(let i = 0; i < 10; i++){fetch('https://playentry.org/graphql', {
	  method: "POST",
	  headers: {"Content-Type": "application/json", "CSRF-Token": csrfToken},
	  body: JSON.stringify({"query":"\n    mutation CREATE_COMMENT(\n        \n    $content: String\n    $image: String\n    $sticker: String\n    $target: String\n    $targetSubject: String\n    $targetType: String\n    $groupId: ID\n\n    ) {\n        createComment(\n            \n    content: $content\n    image: $image\n    sticker: $sticker\n    target: $target\n    targetSubject: $targetSubject\n    targetType: $targetType\n    groupId: $groupId\n\n        ) {\n            warning\n            comment {\n                \n    id\n    user {\n        \n    id\n    nickname\n    username\n    profileImage {\n        \n    id\n    name\n    label {\n        \n    ko\n    en\n    ja\n    vn\n\n    }\n    filename\n    imageType\n    dimension {\n        \n    width\n    height\n\n    }\n    trimmed {\n        filename\n        width\n        height\n    }\n\n    }\n    status {\n        following\n        follower\n    }\n    description\n    role\n\n    }\n    content\n    created\n    removed\n    blamed\n    commentsLength\n    likesLength\n    isLike\n    hide\n    image {\n        \n    id\n    name\n    label {\n        \n    ko\n    en\n    ja\n    vn\n\n    }\n    filename\n    imageType\n    dimension {\n        \n    width\n    height\n\n    }\n    trimmed {\n        filename\n        width\n        height\n    }\n\n    }\n    sticker {\n        \n    id\n    name\n    label {\n        \n    ko\n    en\n    ja\n    vn\n\n    }\n    filename\n    imageType\n    dimension {\n        \n    width\n    height\n\n    }\n    trimmed {\n        filename\n        width\n        height\n    }\n\n    }\n\n            }\n        }\n    }\n","variables":{"content":"콘솔 쓰기!!!","target":"6311ec23c8ce8d0062d036e5","targetSubject":"discuss","targetType":"individual"}})})}}, 61000);
